### ISSUE TITLE
Folding of code block

### ISSUE THREAD

**Issue by xuesoso** [kalekundert/vim-coiled-snake#14]
Hi, thanks for working on this plugin. It works wonder with no performance loss even for large script files. I was wondering if it's possible to add in folding rules for code block? I use jupytext sometimes to view / execute python scripts from jupyter notebooks. So it would be nice to enable folding of code blocks in the markdown file. Below is a screenshot to illustrate the red box which highlights the code block that one would like to fold, as an example.

![image](https://user-images.githubusercontent.com/15006047/75417988-2df5e200-58e7-11ea-85c3-f14e73ab971e.png)

**Comment by kalekundert** [comment]
Sorry it took me a few days to get back to you about this.  It's a good idea, but unfortunately I think it's outside the scope of this plugin.  What would be needed is a markdown plugin that provides some sort of hook that allows third-party plugins to provide folds for code blocks.  This wouldn't be trivial to write, either, because the folds returned by the third-party plugins would need to be changed lest they interfere with the markdown section-based folds.  

The default markdown plugin doesn't hav such a feature, but you could make an issue/PR here:
https://github.com/tpope/vim-markdown
