### ISSUE TITLE
Does not seem to be enabled

### ISSUE THREAD

**Issue by gauteh** [kalekundert/vim-coiled-snake#2]
Hi,

I am trying this plugin with `FastFold` and a bunch of other plugins listed below. But I cannot seem to get it to work. Any tips? I just get no fold detected when trying to collapse a function for instance or collapse all.

```
" Behavior
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'justinmk/vim-sneak'
Plug 'tpope/vim-dispatch', { 'branch' : 'job' }
" Plug 'yuttie/comfortable-motion.vim'
Plug 'junegunn/vim-peekaboo'

" Folding and sessions
" Plug 'farmergreg/vim-lastplace'
Plug 'kopischke/vim-stay'
Plug 'kalekundert/vim-coiled-snake'
Plug 'Konfekt/FastFold'

" Browsing, file management and navigation
Plug 'mhinz/vim-startify'

if !executable('fzf')
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
endif
Plug 'junegunn/fzf.vim'
Plug 'Alok/notational-fzf-vim'
Plug '~/dev/vim/vim-cards'
Plug 'mhinz/vim-grepper'

Plug 'francoiscabrol/ranger.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'roxma/vim-tmux-clipboard'
Plug 'vimwiki/vimwiki'
Plug 'johnsyweb/vim-makeshift'
Plug 'tpope/vim-eunuch'
Plug 'scrooloose/nerdtree'

Plug 'mkitt/tabline.vim'
Plug 'majutsushi/tagbar'

Plug 'mtth/scratch.vim'

" Editing
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'mbbill/undotree'
Plug 'tpope/vim-commentary'
Plug 'godlygeek/tabular'
Plug 'arecarn/vim-crunch'
Plug 'tpope/vim-surround'
Plug 'andymass/vim-matchup'
" Plug 'mg979/vim-yanktools'
Plug 'tpope/vim-endwise'

" Source control
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim'
Plug 'tpope/vim-rhubarb'
Plug 'mhinz/vim-signify'

" Completion
" Plug 'lifepillar/vim-mucomplete'
" Plug 'davidhalter/jedi-vim'
Plug 'SirVer/ultisnips'
  Plug 'honza/vim-snippets'

Plug 'Shougo/deoplete.nvim', { 'do' : ':UpdateRemotePlugins' }
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
" Plug 'tweekmonster/deoplete-clang2'
" Plug 'Rip-Rip/clang_complete'
Plug 'zchee/deoplete-jedi'
Plug 'zchee/deoplete-clang'

" Plug 'Shougo/deoplete-clangx'
Plug 'Shougo/neoinclude.vim'


" Languages and filetypes
Plug 'vim-syntastic/syntastic'
Plug 'ludovicchabant/vim-gutentags'
Plug 'tpope/vim-apathy'

Plug 'lervag/vimtex'
Plug 'gauteh/vim-evince-synctex'
Plug 'adborden/vim-notmuch-address'
Plug 'jamessan/vim-gnupg'
" Plug '~/dev/vim/evince-synctex'

" Color schemes and themeing
Plug 'joshdick/onedark.vim'
Plug 'romainl/Apprentice'
Plug 'rakr/vim-one'
Plug 'endel/vim-github-colorscheme'
Plug 'reedes/vim-colors-pencil'
Plug 'nanotech/jellybeans.vim'
Plug 'roosta/vim-srcery'
Plug 'tyrannicaltoucan/vim-quantum'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()
```

**Comment by kalekundert** [comment]
Sorry for the slow reply, for some reason I didn't get an email notification.  It seems like the incompatibility is with ``kopischke/vim-stay``.  I looked briefly at the code for that plugin, but I haven't been able to really make sense of it yet.

**Comment by kalekundert** [comment]
Ok, I think maybe the problem is just that ``vim-coiled-snake`` wasn't installed when ``vim-stay`` first ran.  Because ``vim-stay`` persists your fold settings, so if ``vim-coiled-snake`` wasn't installed when the settings were saved for a particular file, then ``vim-stay`` will just override ``vim-coiled-snake`` every time it tries to point your fold settings to itself.

For me, I got this folding-does-nothing behavior in the first file I edited after I installed ``vim-stay`` and ``vim-coiled-snake``.   But I haven't had any problems with any files other than that first one.  That's kinda weird, I'm not totally sure what the deal with that is.

For me, the solution was to clear ``vim-stay``'s cache.  To figure out where the cache is located, run vim and enter ``:echo &viewdir``.  This was ``~/.local/share/nvim/view`` for me.  Then just go delete any files in that directory, e.g. ``rm ~/.local/share/nvim/view/*``. 

Let me know if that solves your problem.  I'm still not totally sure what's going on, so I'm not 100% confident that this will work for you.

**Comment by gauteh** [comment]
Kale Kundert writes on August 6, 2018 20:24:
> Sorry for the slow reply, for some reason I didn't get an email notification.  It seems like the incompatibility is with ``kopischke/vim-stay``.  I looked briefly at the code for that plugin, but I haven't been able to really make sense of it yet.
> 

Thanks, I'll try clearing the cache and get back to you.

**Comment by gauteh** [comment]
Gaute Hope writes on August 6, 2018 21:52:
> Kale Kundert writes on August 6, 2018 20:24:
>> Sorry for the slow reply, for some reason I didn't get an email notification.  It seems like the incompatibility is with ``kopischke/vim-stay``.  I looked briefly at the code for that plugin, but I haven't been able to really make sense of it yet.
>> 
> 
> Thanks, I'll try clearing the cache and get back to you.

That did the trick, thanks!

**Comment by kalekundert** [comment]
Awesome, glad I could help!

**Comment by gauteh** [comment]
Since I'm here again, fixed this time by running `:CleanViewDir` with vim-stay installed.
